apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: 9000
            - name: http
              containerPort: 8123
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
            - name: users-config
              mountPath: /etc/clickhouse-server/users.d/users.xml
              subPath: users.xml
{{- if .Values.profiles.enabled }}
            - name: profiles-config
              mountPath: /etc/clickhouse-server/users.d/profiles.xml
              subPath: profiles.xml
{{- end }}
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
{{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
      volumes:
        - name: users-config
          secret:
            secretName: clickhouse-users
{{- if .Values.profiles.enabled }}
        - name: profiles-config
          configMap:
            name: clickhouse-profiles
{{- end }}
  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage.size }}
