apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-users
type: Opaque
stringData:
  users.xml: |
    <clickhouse>
      <users>
      {{- $passwords := .Values.userCredentials | default dict -}}
      {{- range .Values.users }}
        {{- $password := required (printf "userCredentials.%s must be provided (set in values-secret.yaml)" .name) (index $passwords .name) }}
        <{{ .name }}>
          <password>{{ $password }}</password>
          <profile>{{ default "default" .profile }}</profile>
          <quota>{{ default "default" .quota }}</quota>
          <networks>
          {{- range .networks }}
            <ip>{{ . }}</ip>
          {{- end }}
          </networks>
        </{{ .name }}>
      {{- end }}
      </users>
    </clickhouse>
